# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn dependency:copy-dependencies package --file pom.xml


    - name: Upload to ART
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.ART_IP }}
        user: ${{ secrets.ART_USER }}
        pass: ${{ secrets.ART_AUTH }}
        port: 22
        first_ssh: rm ${{ secrets.ART_DIR }}JavaDocSourceEmbed-1.0-SNAPSHOT.jar
        scp: ./target/JavaDocSourceEmbed-1.0-SNAPSHOT.jar => ${{ secrets.ART_DIR }}
